[package]
name = "CorePackages"
authors = ["Roblox"]
license = ""
version = "0.1.0"

[config]
proxy = "https://github.com/roblox/rotriever-proxy-index"

[dependencies]
Roact = { target = "github.com/Roblox/roact-alignment", version = "17.0.1-rc.12", package = "RoactCompat" }
Rodux = "github.com/roblox/rodux@1.0"
RoactRodux = "github.com/roblox/roact-rodux@0.2"
RoactNavigation = "github.com/roblox/roact-navigation@0.5.2"
Cryo = "github.com/roblox/cryo@1.0"
Dash = "github.com/roblox/dash@0.1"
VerifiedBadges = "github.com/roblox/lua-verified-badges@0.1.0"
LuaChatDeps = { git = "https://github.com/Roblox/lua-chat-deps" }
LuaSocialLibrariesDeps = { git = "https://github.com/Roblox/lua-social-libraries-deps" }
PremiumUpsellDeps = { git = "https://github.com/Roblox/premium-upsell-deps" }
AvatarExperienceDeps = { git = "https://github.com/Roblox/avatar-experience-deps" }
LuaProfileDeps_v200 = { git = "https://github.com/Roblox/lua-profile", rev = "v2.0.0", package = "LuaProfileDeps" }
PurchasePromptDeps = { git = "https://github.com/Roblox/purchase-prompt-deps" }
IAPExperience = { git = "https://github.com/Roblox/IAPExperience", rev = "master" }
UIBlox = { git = "https://github.com/Roblox/uiblox", rev = "master" }
Thumbnailing = { git = "https://github.com/Roblox/Thumbnailing", rev = "main" }
Otter = "github.com/roblox/otter@0.1.3"
t = "github.com/roblox/t@1.0"
enumerate = "github.com/roblox/enumerate@1.0.0"
PolicyProvider = { git = "https://github.com/Roblox/lua-roact-policy-provider", rev = "master" }
Lumberyak = { git = "https://github.com/Roblox/lumberyak" }
StringUtilities = "github.com/Roblox/string-utilities@1.0.0"
UrlBuilder = { git = "https://github.com/Roblox/url-builder", rev = "master" }
FitFrame = "github.com/roblox/roact-fit-components@2.0.0"
ExperienceChat = { git = "https://github.com/Roblox/lua-experience-chat", rev = "v1.2.3" }
ExperienceChatV1_3_0 = { git = "https://github.com/Roblox/lua-experience-chat", rev = "v1.3.0" }
RoduxGames = { git = "https://github.com/Roblox/rodux-games", rev = "master" }
React = "github.com/Roblox/roact-alignment@17.0.1-rc.12"
ReactIs = "github.com/Roblox/roact-alignment@17.0.1-rc.12"
ReactRoblox = "github.com/Roblox/roact-alignment@17.0.1-rc.12"
Promise = "github.com/Roblox/roblox-lua-promise@3.3.0"
RoactNavigationUpgradeFlag = { git = "https://github.com/roblox/roact-navigation-upgrade", rev = "v0.1.0", package = "RoactNavigationUpgradeFlag" }
VirtualizedList = { git = "https://github.com/roblox/virtualized-list-lua", rev = "v0.1.0-rc.2" }
LuauPolyfill = { git = "https://github.com/roblox/luau-polyfill", rev = "v0.3.4" }

# The following packages were ported from AppTempCommon
Result = { git = "https://github.com/Roblox/lua-result" }
tutils = { git = "https://github.com/Roblox/tutils" }

InGameMenuDependencies = { git = "https://github.com/Roblox/in-game-menu-dependencies", rev = "master" }

RoactGamepad = "github.com/roblox/roact-gamepad@0.4.6"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.4.0"
Rhodium = "github.com/roblox/rhodium@0.2.8"

# Dependencies for the Roact17 inspector
ReactDevtoolsExtensions = "github.com/Roblox/roact-alignment@17.0.1-rc.12"
DeveloperTools = "github.com/Roblox/developer-tools@0.2.2"

# Patch all dependencies upon rodux to the flagged indireciton package, which
# will ensure that we always use only one rodux version
[config.patch."https://github.com/roblox/rodux"]
Rodux = { git = "https://github.com/roblox/rodux", rev = "v3.0.0" }

[config.patch_git."https://github.com/roblox/roblox-lua-promise"]
Promise = "github.com/Roblox/roblox-lua-promise@3.3.0"

[config.patch_git."https://github.com/roblox/lua-promise"]
Promise = "github.com/Roblox/roblox-lua-promise@3.3.0"

[config.patch."https://github.com/roblox/roact-navigation"]
# RoactNavigation = "github.com/roblox/roact-navigation@0.5.1"
RoactNavigation = { git = "https://github.com/roblox/roact-navigation-upgrade", rev = "v0.1.0", package = "RoactNavigationProxy" }

[config.patch_git."https://github.com/roblox/roact-17-upgrade"]
Roact = { target = "github.com/Roblox/roact-alignment", version = "17.0.1-rc.12", package = "RoactCompat" }
RoactProxy = { target = "github.com/Roblox/roact-alignment", version = "17.0.1-rc.12", package = "RoactCompat" }

# Roact 17 - Patch in flagged proxy for roact, roact-rodux, infinite-scroller, and gamepad
[config.patch."github.com/roblox/roact"]
Roact = { target = "github.com/Roblox/roact-alignment", version = "17.0.1-rc.12", package = "RoactCompat" }

[config.patch."github.com/roblox/roact-rodux"]
RoactRodux = "github.com/Roblox/roact-rodux@0.5.1"

[config.patch."github.com/roblox/infinite-scroller"]
InfiniteScroller = "github.com/Roblox/infinite-scroller@0.9.5"

[config.patch."github.com/roblox/roact-gamepad"]
RoactGamepad = "github.com/Roblox/roact-gamepad@0.5.3"
